### ISSUE TITLE
Unable to run run_dalla_auto_revision.py

### ISSUE THREAD

**Issue by RadenFaqih** [geoenvo/jaksafe-engine#13]
Ketika run_dalla_auto_revision.py diexecute, muncul error berupa:
    `"not enough arguments for format string"`

Setelah dilakukan debug, perhitungan terhenti pada code berikut:
`sql_query_final = sql_query%data`

Lengkapnya:

```
def inserting_table_dala_result_auto(last_id_auto_event,psql_db_con,input_sql_folder):
    sql_file = input_sql_folder + '/' + 'sql_query_dala_aset_auto.txt'
    sql_query = open(sql_file, 'r').read()

    list_data = []
    for i in range(57):
        list_data.append(last_id_auto_event)    
    data = tuple(list_data)

    sql_query_final = sql_query%data
    cur = psql_db_con.cursor()
    cur.execute(sql_query_final)
    psql_db_con.commit()
```

Code tersebut ada pada file:
_../jaksafe-engine/jaksafe/jaksafe/jakservice/impact_analysis/hazard_compilation_function.py_

Ketika dicek query-nya pada sql_file:
    _sql_query_dala_aset_auto.txt_

ternyata jumlah (%s) di sana ada sebanyak 64. Sehingga dilakukan run ulang dengan mengubah:

```
    for i in range(64):
```

Kemudian setelah dirun ulang, masih didapatkan error berupa:

```
Error syntax error at or near "34.0"
    LINE 178: ...adhoc_luas_banjir where id_event=(24))/264.0)*(24)34.0*12(24...
                                                                   ^
```

Code lengkap pada LINE 178 adalah sebagai berikut:

```
    --c. hitung kerusakan kendaraan (insert kedalam table adhc_kerusakan_kendaraan)
    insert into adhoc_kerusakan_kendaraan (id_event, kerusakan_kendaraan)
    select cast((%s) as int) id_event,
    (((select jumlah_rw_banjir from adhoc_luas_banjir where id_event=(%s))/264.0)*(%s)34.0*12(%s).0*0.0(%s)*109000.0)+
    (((select jumlah_rw_banjir from adhoc_luas_banjir where id_event=(%s))/264.0)*(%s)34.0*12(%s).0*0.78*2390000.0)+
    (((select jumlah_rw_banjir from adhoc_luas_banjir where id_event=(%s))/264.0)*(%s)34.0*12(%s).0*0.17*2390000.0)
    kerusakan_kendaraan; 
```

berada pada file:
_../jaksafe-engine/jaksafe/jaksafe/jakservice/auto/input/sql/sql_query_dala_aset_auto.txt_

Apakah syntaxnya memang seperti itu atau perlu tambahan operator perhitungan tertentu pada (%s)34.0*12(%s) ?

**Comment by frzdian** [comment]
%s itu hanya untuk menggantikan id_event, kayanya saya salah waktu replace value id_event. coba diganti dengan 

--c. hitung kerusakan kendaraan (insert kedalam table adhc_kerusakan_kendaraan)
insert into auto_kerusakan_kendaraan (id_event, kerusakan_kendaraan)
select cast(%s as int) id_event,
(((select jumlah_rw_banjir from auto_luas_banjir where id_event=%s)/264.0) \* 534.0 \* 1.25 \* 0.05 \* 109000.0)+
(((select jumlah_rw_banjir from auto_luas_banjir where id_event=%s)/264.0) \* 534.0 \* 1.25 \* 0.78 \* 2390000.0)+
(((select jumlah_rw_banjir from auto_luas_banjir where id_event=%s)/264.0) \* 534.0 \* 1.25 \* 0.17 \* 2390000.0)
kerusakan_kendaraan;

**Comment by RadenFaqih** [comment]
Apakah benar pakai ?
`insert into auto_....`

karena di bagian yang lain, semuanya menggunakan
`insert into adhoc_....`

Apakah perlu saya replace semuanya dari `adhoc` ke `auto`?

[sql_query_dala_aset.txt](https://github.com/geoenvo/jaksafe-engine/blob/master/jaksafe/jaksafe/jakservice/auto/input/sql/sql_query_dala_aset.txt)
[sql_query_dala_aset_auto.txt](https://github.com/geoenvo/jaksafe-engine/blob/master/jaksafe/jaksafe/jakservice/auto/input/sql/sql_query_dala_aset_auto.txt)

**Comment by RadenFaqih** [comment]
Issue sudah solve. 
Ternyata harus merubah `adhoc` menjadi `auto` pada file:
[sql_query_dala_aset_auto.txt](https://github.com/geoenvo/jaksafe-engine/blob/master/jaksafe/jaksafe/uploaded/jakservice/auto/input/sql/sql_query_dala_aset_auto.txt)
[sql_query_dala_summary_auto.txt](https://github.com/geoenvo/jaksafe-engine/blob/master/jaksafe/jaksafe/uploaded/jakservice/auto/input/sql/sql_query_dala_summary_auto.txt)
