### ISSUE TITLE
Jakservice auto_dala_result

### ISSUE THREAD

**Issue by RadenFaqih** [geoenvo/jaksafe-engine#9]
![auto_dala_result damage n loss null 2](https://cloud.githubusercontent.com/assets/16549918/15668666/a230c68e-2746-11e6-8f71-6532cca3e397.jpg)

Jakservice masih mengeluarkan nilai NULL pada database PostgreSQL, table auto_dala_result, kolom damage & loss, untuk asset KENDARAAN

**Comment by mf4dl1** [comment]
@miarenauly bisa bantu analisa hal ini?

**Comment by miarenauly** [comment]
kalau untuk loss asset KENDARAAN itu masih ada yang NULL karena ternyata saya cek di Database utamanya (tabel road), ada informasi yang masih kosong. Nanti bisa diupdate di database postgreSQL nya yang di production. Tapi kalau yang asset KERUSAKAN itu saya ga tau ngambilnya dari database mana, mungkin @frzdian atau @keziavelda tau kah?

**Comment by keziavelda** [comment]
perhitungan kerusakan kendaraan dilakukan dengan query berikut

`--c. hitung kerusakan kendaraan (insert kedalam table adhc_kerusakan_kendaraan)
insert into adhoc_kerusakan_kendaraan (id_event, kerusakan_kendaraan)
select cast(%s as int) id_event,
(((select jumlah_rw_banjir from adhoc_luas_banjir where id_event=%s)/264.0)*534.0*1.25*0.05*109000.0)+
(((select jumlah_rw_banjir from adhoc_luas_banjir where id_event=%s)/264.0)*534.0*1.25*0.78*2390000.0)+
(((select jumlah_rw_banjir from adhoc_luas_banjir where id_event=%s)/264.0)*534.0*1.25*0.17*2390000.0)
kerusakan_kendaraan;
`

sesuai dengan logic asumsi kendaraan yang pernah diberikan oleh @miarenauly , sbb:
`Total Kendaraan Rusak = (Jumlah RW yang terkena Banjir/264)_534_125

Kerusakan Motor= Total Kendaraan Rusak \* 5% \* 109000
Kerusakan Mobil= Total Kendaraan Rusak \* 78% \* 2390000
Kerusakan Bus= Total Kendaraan Rusak \* 17% \*  2390000

Kerusakan KENDARAAN =  Kerusakan Motor + Kerusakan Mobil + Kerusakan Bus`

jadi untuk menghitung kerusakan kendaraan ini hanya menggunakan informasi dari tabel adoc_luas_banjir.

**Comment by RadenFaqih** [comment]
Nilai damage dan loss yang **NULL** apakah boleh diisi dengan nilai **0** sebagai **default value** ?
Tujuannya adalah untuk mempermudah perhitungan total damage & loss per row di tabel auto_dala_result.
